### PR TITLE
JS origins -> redirect URIs

### PR DESCRIPTION
**Pull request by ace-n**
In response to a customer bug. Similar to [this PR](https://github.com/GoogleCloudPlatform/community/pull/903).

### CODE REVIEW

**Comment by ace-n** [comment]
cc @erickoledadevrel (or one of the other G Suite folks)

**Comment by erickoledadevrel** [comment]
What can I do you for? Is this a larger issue we should be aware of?

**Comment by ace-n** [comment]
Nope - just a PR review. I wanted to make sure this change was conceptually
correct.

**Comment by erickoledadevrel** [comment]
LGTM

**Pull request merged**
